name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm config set //npm.pkg.github.com/:_authToken $TOKEN
          npm install
          npm run build
          npm test
          npm publish
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
